### ISSUE TITLE
Snap issue

### ISSUE THREAD

**Issue by ItsmagmaMan09** [TubYoub/VelocityPteroPower#8]
My server boots up fine and the plugin starts with no errors but when i connect to a server i get a warn message from snap and then just some error that seems related to the snap warn and the request server wont start. It could be my config but I'm not sure.

> [20:43:08 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@29e341e8, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener de.themoep.serverstatus.ServerSwitchListener@1f6140f8
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because "server" is null
        at de.themoep.serverstatus.ServerStatusChecker.getStatus(ServerStatusChecker.java:169) ~[?:?]
        at de.themoep.serverstatus.ServerSwitchListener.onServerSwitch(ServerSwitchListener.java:39) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$49.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEv
entManager.java:676) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[velocity.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

[config.txt](https://github.com/user-attachments/files/17788714/config.txt)

**Comment by TubYoub** [comment]
Hi,
If you still connect to the server then it is no issue with my plyugin but rather one with the integration from snap

**Comment by ItsmagmaMan09** [comment]
The server wont start either, and it leaves a join request active until i start the server manually so i think the plugin is just failing to reach the panel or start the server. but i do believe i have the config set correctly.

**Comment by TubYoub** [comment]
Could you send me the full server logs?
https://mclo.gs/

**Comment by ItsmagmaMan09** [comment]
yea, https://mclo.gs/uhCbFTu
there is some weird geyser issue but i think its unrelated

**Comment by TubYoub** [comment]
This is defenetly some issue with snap, its not handeling the connection proberly and in response it doesnt connect the player

**Comment by ItsmagmaMan09** [comment]
I'd agree it's an issue with snap but what I wonder is why it just can't flat out reach the panel cause I'd assume other people don't have this issue, and then when I did start the server that the player requested myself, once it starts the player does get sent so it's just some weird communication thing with the panel

**Comment by TubYoub** [comment]
i just noticed that you are using the pelican panel, maybe i have an error with the communication there let me have a look

**Comment by ItsmagmaMan09** [comment]
alright, let me know what you find

**Comment by TubYoub** [comment]
Hi, 
I made a issue in the config you need a client API key and not an Application key. 
Go to your profile > API Keys 
If that doesnt solve the issue ill look into setting up a peli panel myself for testing currently i am only working with the docs thats why i cant rly test

**Comment by ItsmagmaMan09** [comment]
Yes, using a profile API key worked just fine only issue is that snap still produces an error witch can just be suppressed with a java argument for now. Otherwise it works great i think it was my fault for assuming it was a panel key and not a profile key!

**Comment by TubYoub** [comment]
Great, but i will still fix the wording in future releases. 
But please report the error to snap so it can get fixed.
